// Generated by `pnpm tokens` from packages/ui/tokens (DTCG 2025.10): edit those, not this.

/** The spacing scale (--space-*): Stack, Inline and Tiles take these names. */
export const SPACE = ["2xs", "xs", "sm", "md", "lg", "xl", "2xl", "3xl"] as const;
export type SpaceName = (typeof SPACE)[number];
/** The type scale (--text-*). */
export const TEXT_SIZES = ["2xs", "xs", "sm", "md", "base", "lg", "xl", "display"] as const;
export type TextSize = (typeof TEXT_SIZES)[number];
/** Corner radii (--radius-*; --radius itself for controls and rows). */
export const RADII = ["xs", "sm", "md", "lg", "xl", "pill"] as const;
export type RadiusName = (typeof RADII)[number];

/** What light themes override (appearance-light.tokens.json), by name without the dashes. */
export const LIGHT_VARS: Readonly<Record<string, string>> = {
  "shadow": "rgb(0 0 0 / 0.18)",
  "field": "var(--well)",
  "recess": "color-mix(in srgb, var(--ink) 3.5%, transparent)",
  "recess-edge": "color-mix(in srgb, var(--ink) 8%, transparent)",
  "pane-edge": "color-mix(in srgb, var(--ink) 10%, transparent)",
  "chip-fg": "55% 38%",
  "chip-bg": "60% 92%",
  "avatar": "62% 56%",
  "control-thumb": "color-mix(in srgb, #fff 65%, var(--bg-elevated))",
  "control-thumb-shadow": "0 1px 2px rgb(0 0 0 / 0.16), 0 0 0 0.5px rgb(0 0 0 / 0.14)",
  "window-dim": "0.25"
};

export interface TokenInfo {
  name: string;
  type?: string;
  /** Its CSS value, or `theme: <source>` for what the active theme sets. */
  value: string;
  description?: string;
  /** Its value in light themes, where they override it. */
  light?: string;
}

/** Every token, in the order of its files: for the gallery, docs and agents. */
export const TOKENS: readonly TokenInfo[] = [
  {
    "name": "--bg",
    "type": "color",
    "value": "theme: colors.bg",
    "description": "The board and toolbars."
  },
  {
    "name": "--bg-sidebar",
    "type": "color",
    "value": "theme: colors.bgSidebar",
    "description": "Sidebars and title bars."
  },
  {
    "name": "--bg-elevated",
    "type": "color",
    "value": "theme: colors.bgElevated",
    "description": "The palette, popovers, menus."
  },
  {
    "name": "--well",
    "type": "color",
    "value": "theme: colors.well",
    "description": "Window content: terminals, editors, lists, tables. A window's body."
  },
  {
    "name": "--text",
    "type": "color",
    "value": "theme: colors.text",
    "description": "Primary text."
  },
  {
    "name": "--text-dim",
    "type": "color",
    "value": "theme: colors.textDim",
    "description": "Secondary text: descriptions, labels, values that support the main one."
  },
  {
    "name": "--icon",
    "type": "color",
    "value": "theme: colors.icon",
    "description": "Icons at rest."
  },
  {
    "name": "--accent",
    "type": "color",
    "value": "theme: colors.accent",
    "description": "The one highlight colour: the selected window, the primary button, focus."
  },
  {
    "name": "--link",
    "type": "color",
    "value": "theme: colors.link",
    "description": "Links and folders."
  },
  {
    "name": "--match",
    "type": "color",
    "value": "theme: colors.match",
    "description": "Search matches (used translucent)."
  },
  {
    "name": "--ink",
    "type": "color",
    "value": "theme: colors.ink",
    "description": "What hover, selection, separators and outlines are mixed from: white on dark themes, black on light ones."
  },
  {
    "name": "--scrim",
    "type": "color",
    "value": "theme: colors.scrim",
    "description": "Dimming overlays and recessed areas: usually black."
  },
  {
    "name": "--state-needs",
    "type": "color",
    "value": "theme: colors.stateNeeds",
    "description": "An agent or task needs you (amber)."
  },
  {
    "name": "--state-done",
    "type": "color",
    "value": "theme: colors.stateDone",
    "description": "Done, good, passing (green)."
  },
  {
    "name": "--state-working",
    "type": "color",
    "value": "theme: colors.stateWorking",
    "description": "Working, running (blue)."
  },
  {
    "name": "--state-idle",
    "type": "color",
    "value": "theme: colors.stateIdle",
    "description": "Idle, off (grey)."
  },
  {
    "name": "--syn-keyword",
    "type": "color",
    "value": "theme: syntax.keyword",
    "description": "Editor and Markdown syntax: keyword (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-string",
    "type": "color",
    "value": "theme: syntax.string",
    "description": "Editor and Markdown syntax: string (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-number",
    "type": "color",
    "value": "theme: syntax.number",
    "description": "Editor and Markdown syntax: number (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-comment",
    "type": "color",
    "value": "theme: syntax.comment",
    "description": "Editor and Markdown syntax: comment (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-function",
    "type": "color",
    "value": "theme: syntax.function",
    "description": "Editor and Markdown syntax: function (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-type",
    "type": "color",
    "value": "theme: syntax.type",
    "description": "Editor and Markdown syntax: type (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-property",
    "type": "color",
    "value": "theme: syntax.property",
    "description": "Editor and Markdown syntax: property (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-heading",
    "type": "color",
    "value": "theme: syntax.heading",
    "description": "Editor and Markdown syntax: heading (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-punct",
    "type": "color",
    "value": "theme: syntax.punct",
    "description": "Editor and Markdown syntax: punct (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-cursor",
    "type": "color",
    "value": "theme: syntax.cursor",
    "description": "Editor and Markdown syntax: cursor (the theme's, else from its terminal colours)."
  },
  {
    "name": "--syn-selection",
    "type": "color",
    "value": "theme: syntax.selection",
    "description": "Editor and Markdown syntax: selection (the theme's, else from its terminal colours)."
  },
  {
    "name": "--git-added",
    "type": "color",
    "value": "theme: terminal (git added)",
    "description": "A file that is added in git (from the terminal colours)."
  },
  {
    "name": "--git-modified",
    "type": "color",
    "value": "theme: terminal (git modified)",
    "description": "A file that is modified in git (from the terminal colours)."
  },
  {
    "name": "--git-deleted",
    "type": "color",
    "value": "theme: terminal (git deleted)",
    "description": "A file that is deleted in git (from the terminal colours)."
  },
  {
    "name": "--git-conflict",
    "type": "color",
    "value": "theme: terminal (git conflict)",
    "description": "A file that is conflict in git (from the terminal colours)."
  },
  {
    "name": "--chart-1",
    "type": "color",
    "value": "theme: terminal.blue",
    "description": "Chart series 1, used in order (Chart, Sparkline). The terminal's blue, as Magic's --c1."
  },
  {
    "name": "--chart-2",
    "type": "color",
    "value": "theme: terminal.green",
    "description": "Chart series 2, used in order (Chart, Sparkline). The terminal's green, as Magic's --c2."
  },
  {
    "name": "--chart-3",
    "type": "color",
    "value": "theme: terminal.yellow",
    "description": "Chart series 3, used in order (Chart, Sparkline). The terminal's yellow, as Magic's --c3."
  },
  {
    "name": "--chart-4",
    "type": "color",
    "value": "theme: terminal.magenta",
    "description": "Chart series 4, used in order (Chart, Sparkline). The terminal's magenta, as Magic's --c4."
  },
  {
    "name": "--chart-5",
    "type": "color",
    "value": "theme: terminal.cyan",
    "description": "Chart series 5, used in order (Chart, Sparkline). The terminal's cyan, as Magic's --c5."
  },
  {
    "name": "--chart-6",
    "type": "color",
    "value": "theme: terminal.red",
    "description": "Chart series 6, used in order (Chart, Sparkline). The terminal's red, as Magic's --c6."
  },
  {
    "name": "--font-ui",
    "type": "fontFamily",
    "value": "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", system-ui, sans-serif",
    "description": "Labels, controls, sentences."
  },
  {
    "name": "--font-mono",
    "type": "fontFamily",
    "value": "\"SF Mono\", \"Menlo\", monospace",
    "description": "Values, numbers, IDs, paths, commands, code: anything that is data rather than a label."
  },
  {
    "name": "--text-2xs",
    "type": "dimension",
    "value": "10px",
    "description": "Chart ticks and the smallest notes. Never for something you read."
  },
  {
    "name": "--text-xs",
    "type": "dimension",
    "value": "10.5px",
    "description": "Section headings (caps), badges."
  },
  {
    "name": "--text-sm",
    "type": "dimension",
    "value": "11.5px",
    "description": "Descriptions, a row's second line, footers and status lines."
  },
  {
    "name": "--text-md",
    "type": "dimension",
    "value": "12.5px",
    "description": "Controls, list rows, tables: the default in windows."
  },
  {
    "name": "--text-base",
    "type": "dimension",
    "value": "13px",
    "description": "Body copy: prose, a dialog's text."
  },
  {
    "name": "--text-lg",
    "type": "dimension",
    "value": "15px",
    "description": "A metric's value (Stat); an empty state's title."
  },
  {
    "name": "--text-xl",
    "type": "dimension",
    "value": "17px",
    "description": "A document's title. At most one per window."
  },
  {
    "name": "--text-display",
    "type": "dimension",
    "value": "20px",
    "description": "A sheet's greeting (SheetHeader), once per screen."
  },
  {
    "name": "--space-2xs",
    "type": "dimension",
    "value": "2px",
    "description": "2px: a value and its unit, a label and its value in a Stat."
  },
  {
    "name": "--space-xs",
    "type": "dimension",
    "value": "4px",
    "description": "4px: lines in a group (a title and its detail); a list's padding above and below."
  },
  {
    "name": "--space-sm",
    "type": "dimension",
    "value": "6px",
    "description": "6px: items in a row (an icon and its label, a dot and its word)."
  },
  {
    "name": "--space-md",
    "type": "dimension",
    "value": "8px",
    "description": "8px: an icon and a row's text; controls side by side; the default Stack gap."
  },
  {
    "name": "--space-lg",
    "type": "dimension",
    "value": "12px",
    "description": "12px: the window inset (--inset); between groups of a toolbar or status line."
  },
  {
    "name": "--space-xl",
    "type": "dimension",
    "value": "16px",
    "description": "16px: between sections of a list or inspector; between columns of a table (2 × 8)."
  },
  {
    "name": "--space-2xl",
    "type": "dimension",
    "value": "24px",
    "description": "24px: between a dashboard's panes; above a document's column."
  },
  {
    "name": "--space-3xl",
    "type": "dimension",
    "value": "32px",
    "description": "32px: below a document's column. Rarely anything else."
  },
  {
    "name": "--inset",
    "value": "var(--space-lg)",
    "description": "A window's content inset, on every side, measured to the letters: a padded body, the first and last table column, list rows' content, footer text. One value for every window."
  },
  {
    "name": "--measure",
    "value": "68ch",
    "description": "Reading width for prose: a document's column (Measure)."
  },
  {
    "name": "--control-h-sm",
    "type": "dimension",
    "value": "20px",
    "description": "Small controls: buttons in a row, inline actions."
  },
  {
    "name": "--control-h",
    "type": "dimension",
    "value": "24px",
    "description": "Controls: buttons, fields, popups. Every control in a row shares one height, so they line up."
  },
  {
    "name": "--control-h-lg",
    "type": "dimension",
    "value": "28px",
    "description": "Large controls: a sheet's primary action."
  },
  {
    "name": "--disabled-opacity",
    "type": "number",
    "value": "0.4",
    "description": "A disabled control."
  },
  {
    "name": "--row-h-sm",
    "type": "dimension",
    "value": "22px",
    "description": "Compact rows: dense trees."
  },
  {
    "name": "--row-h",
    "type": "dimension",
    "value": "24px",
    "description": "Table rows (DataGrid) and one-line list rows."
  },
  {
    "name": "--row-h-lg",
    "type": "dimension",
    "value": "28px",
    "description": "Sidebar rows."
  },
  {
    "name": "--radius-xs",
    "type": "dimension",
    "value": "3px",
    "description": "Inner shapes: a filmstrip thumbnail, an image on a stage."
  },
  {
    "name": "--radius-sm",
    "type": "dimension",
    "value": "4px",
    "description": "Small controls inside others: a toolbar item, a chip."
  },
  {
    "name": "--radius",
    "type": "dimension",
    "value": "6px",
    "description": "Controls and rows (hover pills). Inner shapes in padding are concentric: radius − padding."
  },
  {
    "name": "--radius-md",
    "type": "dimension",
    "value": "8px",
    "description": "Cards, callouts, group boxes."
  },
  {
    "name": "--radius-lg",
    "type": "dimension",
    "value": "10px",
    "description": "Menus, popovers."
  },
  {
    "name": "--radius-xl",
    "type": "dimension",
    "value": "12px",
    "description": "Dialogs, the palette."
  },
  {
    "name": "--radius-pill",
    "type": "dimension",
    "value": "999px",
    "description": "Badges, pills."
  },
  {
    "name": "--text-faint",
    "type": "color",
    "value": "color-mix(in srgb, var(--text-dim) 70%, transparent)",
    "description": "Fainter than --text-dim: what a window's footer says (counts, when it updated)."
  },
  {
    "name": "--bg-hover",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 6%, transparent)"
  },
  {
    "name": "--bg-selected",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 10%, transparent)"
  },
  {
    "name": "--separator",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 9%, transparent)"
  },
  {
    "name": "--on-accent",
    "type": "color",
    "value": "#ffffff",
    "description": "text on an accent background"
  },
  {
    "name": "--folder",
    "value": "var(--link)"
  },
  {
    "name": "--shadow",
    "type": "color",
    "value": "rgb(0 0 0 / 0.5)",
    "light": "rgb(0 0 0 / 0.18)"
  },
  {
    "name": "--field",
    "type": "color",
    "value": "color-mix(in srgb, var(--scrim) 28%, transparent)",
    "description": "Recessed fields (settings window) and project chips (lightness for hsl(var(--hue) …)).",
    "light": "var(--well)"
  },
  {
    "name": "--field-bg",
    "value": "var(--well)"
  },
  {
    "name": "--field-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 24%, var(--field-bg))",
    "description": "Text fields' edge: stronger than a button's, since the well is darker than the surface around it. Opaque (mixed over the field's own fill, which every theme sets as a solid colour), so where two edges meet, as in a joined SecretField, they don't add up darker."
  },
  {
    "name": "--pane-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--scrim) 50%, transparent)",
    "description": "Dividers between a window's panes (the Settings window's sidebar and bar).",
    "light": "color-mix(in srgb, var(--ink) 10%, transparent)"
  },
  {
    "name": "--recess",
    "type": "color",
    "value": "color-mix(in srgb, var(--scrim) 22%, transparent)",
    "description": "Recessed areas: unassigned grid cells.",
    "light": "color-mix(in srgb, var(--ink) 3.5%, transparent)"
  },
  {
    "name": "--recess-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--scrim) 35%, transparent)",
    "light": "color-mix(in srgb, var(--ink) 8%, transparent)"
  },
  {
    "name": "--chip-fg",
    "value": "70% 78%",
    "light": "55% 38%"
  },
  {
    "name": "--chip-bg",
    "value": "30% 22% / 0.8",
    "light": "60% 92%"
  },
  {
    "name": "--avatar",
    "value": "58% 52%",
    "description": "Avatars (the Widget Library's cards): saturation and lightness of a full-colour tile, with hsl(var(--hue) …).",
    "light": "62% 56%"
  },
  {
    "name": "--group-bg",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 3.5%, transparent)",
    "description": "Grouped lists (a Settings section): a faint fill and hairline."
  },
  {
    "name": "--group-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 6%, transparent)"
  },
  {
    "name": "--popover-bg",
    "value": "var(--bg-elevated)",
    "description": "Floating surfaces: menus, popovers, dialogs, tooltips."
  },
  {
    "name": "--popover-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 12%, transparent)"
  },
  {
    "name": "--popover-shadow",
    "value": "0 10px 30px var(--shadow)"
  },
  {
    "name": "--code-bg",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 5%, transparent)",
    "description": "Code and output blocks."
  },
  {
    "name": "--danger",
    "value": "var(--git-deleted, #ff453a)"
  },
  {
    "name": "--warning",
    "value": "var(--state-needs)"
  },
  {
    "name": "--success",
    "value": "var(--state-done)"
  },
  {
    "name": "--info",
    "value": "var(--accent)"
  },
  {
    "name": "--input-bg",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 5%, transparent)",
    "description": "Text inputs, system style: a faint fill and hairline edge; on focus the edge takes some accent and a soft halo surrounds it, rather than a hard accent line."
  },
  {
    "name": "--input-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 10%, transparent)"
  },
  {
    "name": "--input-focus-edge",
    "type": "color",
    "value": "color-mix(in srgb, var(--accent) 50%, var(--field-edge))",
    "description": "opaque, like the field edge it replaces"
  },
  {
    "name": "--input-glow",
    "type": "color",
    "value": "color-mix(in srgb, var(--accent) 20%, transparent)"
  },
  {
    "name": "--input-ring",
    "value": "inset 0 0 0 1px var(--input-focus-edge), 0 0 0 3px var(--input-glow)"
  },
  {
    "name": "--input-placeholder",
    "value": "var(--text-dim)"
  },
  {
    "name": "--control-bg",
    "value": "var(--input-bg)",
    "description": "Buttons, popups, segmented controls share a fill; text fields sit in the well."
  },
  {
    "name": "--control-edge",
    "value": "var(--input-edge)"
  },
  {
    "name": "--control-hover",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 10%, transparent)"
  },
  {
    "name": "--control-active",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 14%, transparent)"
  },
  {
    "name": "--control-thumb",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 16%, transparent)",
    "description": "The chosen segment: a lift over the track, so it shows on any surface (a window, a dialog).",
    "light": "color-mix(in srgb, #fff 65%, var(--bg-elevated))"
  },
  {
    "name": "--control-thumb-shadow",
    "value": "0 1px 2px rgb(0 0 0 / 0.22), inset 0 0 0 1px color-mix(in srgb, var(--ink) 8%, transparent)",
    "light": "0 1px 2px rgb(0 0 0 / 0.16), 0 0 0 0.5px rgb(0 0 0 / 0.14)"
  },
  {
    "name": "--switch-off",
    "type": "color",
    "value": "color-mix(in srgb, var(--ink) 16%, transparent)"
  },
  {
    "name": "--knob",
    "type": "color",
    "value": "#ffffff"
  },
  {
    "name": "--footer-h",
    "type": "dimension",
    "value": "26px",
    "description": "A window's footer bar (View footer): one line of status in --text-faint, the same top line as the toolbar's (--window-edge)."
  },
  {
    "name": "--window-radius",
    "type": "dimension",
    "value": "8px",
    "description": "Windows (window.tsx) and sheets (Dialog): rounded corners and crisp whole-pixel outlines, the selected one in the highlight with a soft glow, and an elevation shadow. An app maps these to its own settings (cmd: the ui.window* settings, look.ts): --window-radius, --window-outline, --window-edge-mix (the outline's contrast), --window-elevation, --focus-outline, --focus-glow (1 = the default halo). What's built from them is declared again on .ui-window, where an app's per-mode values resolve."
  },
  {
    "name": "--window-outline",
    "type": "dimension",
    "value": "1px"
  },
  {
    "name": "--window-elevation",
    "type": "number",
    "value": "0.5"
  },
  {
    "name": "--window-edge",
    "value": "color-mix(in srgb, var(--ink) var(--window-edge-mix, 9%), var(--bg-sidebar))",
    "description": "The outline and the line under the title bar: one opaque colour (the separator over the title bar), so both look the same over any background."
  },
  {
    "name": "--window-highlight",
    "value": "var(--accent)"
  },
  {
    "name": "--window-bg",
    "value": "var(--well)"
  },
  {
    "name": "--window-bar-h",
    "type": "dimension",
    "value": "26px",
    "description": "The title bar."
  },
  {
    "name": "--window-bar-bg",
    "value": "var(--bg-sidebar)"
  },
  {
    "name": "--window-dim",
    "type": "number",
    "value": "1",
    "description": "How much this theme darkens unfocused windows: a factor on the ui.unfocusedDim setting.",
    "light": "0.25"
  },
  {
    "name": "--focus-outline",
    "type": "dimension",
    "value": "1px"
  },
  {
    "name": "--focus-glow",
    "type": "number",
    "value": "1"
  },
  {
    "name": "--toolbar-h",
    "type": "dimension",
    "value": "31px",
    "description": "The window toolbar (WindowToolbar), with its 1px line. A row that holds controls is a toolbar, not part of the body."
  },
  {
    "name": "--toolbar-item-h",
    "type": "dimension",
    "value": "22px",
    "description": "Items in the window toolbar."
  },
  {
    "name": "--toolbar-bg",
    "value": "var(--bg)"
  },
  {
    "name": "--sheet-radius",
    "value": "var(--window-radius)",
    "description": "Sheets look like windows: their corners, outline and the same shadow, higher (4× the windows' elevation, at most 6)."
  },
  {
    "name": "--sheet-edge-width",
    "value": "var(--window-outline)"
  },
  {
    "name": "--sheet-edge",
    "value": "var(--window-edge)"
  },
  {
    "name": "--sheet-elev",
    "value": "min(6, calc(var(--window-elevation) * 4))"
  },
  {
    "name": "--sheet-sh",
    "type": "color",
    "value": "color-mix(in oklab, var(--shadow) 85%, var(--bg))"
  },
  {
    "name": "--sheet-shadow",
    "value": "0 calc(0.5px * var(--sheet-elev)) calc(1px * var(--sheet-elev)) color-mix(in srgb, var(--sheet-sh) 36%, transparent), 0 calc(1px * var(--sheet-elev)) calc(2px * var(--sheet-elev)) color-mix(in srgb, var(--sheet-sh) 30%, transparent), 0 calc(2px * var(--sheet-elev)) calc(4px * var(--sheet-elev)) color-mix(in srgb, var(--sheet-sh) 24%, transparent), 0 calc(4px * var(--sheet-elev)) calc(8px * var(--sheet-elev)) calc(-1px * var(--sheet-elev)) color-mix(in srgb, var(--sheet-sh) 20%, transparent), 0 calc(8px * var(--sheet-elev)) calc(16px * var(--sheet-elev)) calc(-2px * var(--sheet-elev)) color-mix(in srgb, var(--sheet-sh) 16%, transparent)"
  },
  {
    "name": "--ease",
    "type": "cubicBezier",
    "value": "cubic-bezier(0.2, 0.8, 0.2, 1)",
    "description": "(motion.ts MOTION has the same values; a test keeps them equal) exit: something leaving, and quick pops in. change: a state changing (a ring, a size). slow: an indicator (a progress, a dot). glide: something moving (below)."
  },
  {
    "name": "--ease-exit",
    "type": "cubicBezier",
    "value": "cubic-bezier(0.4, 0, 1, 1)"
  },
  {
    "name": "--dur-fast",
    "type": "duration",
    "value": "120ms"
  },
  {
    "name": "--dur",
    "type": "duration",
    "value": "150ms"
  },
  {
    "name": "--dur-slow",
    "type": "duration",
    "value": "240ms"
  },
  {
    "name": "--glide",
    "value": "linear(0 0%, 0.0016 0.6%, 0.0134 1.9%, 0.0442 3.6%, 0.0979 5.7%, 0.1735 8.1%, 0.2659 10.9%, 0.368 13.9%, 0.4724 17.2%, 0.5724 20.8%, 0.6633 24.6%, 0.742 28.7%, 0.8075 33%, 0.86 37.5%, 0.9006 42.2%, 0.9311 47.1%, 0.9533 52.3%, 0.969 57.6%, 0.9799 63.1%, 0.9872 68.8%, 0.992 74.7%, 0.9951 80.8%, 0.9971 87%, 0.9983 93.4%, 1 100%)",
    "description": "Moving a window or a view: a critically damped spring (no bounce) sampled for CSS, the curve the app's TileMotion runs in JS (apps/desktop motion.ts, GLIDE_MS)."
  },
  {
    "name": "--glide-dur",
    "type": "duration",
    "value": "382ms"
  }
];
