export { runMagic, fastRoute, type MagicOptions, type MagicResult, type MagicEvent, type TraceStep } from "./run.ts";
export { aiBackend, backendFor, claudeCliBackend, claudeCliAvailable, DEFAULT_MODEL, type Backend, type Usage } from "./backends.ts";
export { MagicService } from "./service.ts";
export { parseAnswer, AnswerStream, type MagicHeader } from "./contract.ts";
export { classify, credentialsFor, DEFAULT_DENY_PATHS, isDeniedPath, redact } from "./policy.ts";
export { execCommand, sandboxAvailable, sandboxProfile, type SandboxMode } from "./sandbox.ts";
export { runSource, preview, type MagicSource, type SourceResult } from "./sources.ts";
export { TOOL_SPECS, toolsFor, runTool } from "./tools.ts";
export { buildSystem, buildRequest, PROMPT_DIR } from "./prompt.ts";
export { widgetHtml, widgetTokens, SIZES, type ThemeLike } from "./host.ts";
export { serveMcp } from "./mcp.ts";
